version: "3"
services:
  php71:
    container_name: php71
    build:
      context: ./config/php/
      args:
        PHP_VERSION: ${PHP71_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP71_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php71.sh
        TZ: "$TZ"
    ports:
      - "${PHP71_HOST_PORT}:9000"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP71_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP71_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP71_LOG_DIR}:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

networks:
  default:


