version: "3"
services:
  python3:
    container_name: python3
    build:
      context: ./config/python/
      args:
        PYTHON_VERSION: ${PYTHON3_VERSION}
        TZ: "$TZ"
    ports:
      - "${PYTHON3_HOST_PORT}:10000"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - default

networks:
  default: